apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  type: ClusterIP
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 10.0.0.10

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    tier: frontend
spec:
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: wordpress
          image: wordpress
          ports:
          - containerPort: 80
          env:
           - name: WORDPRESS_DB_NAME
             value: wordpress
           - name: WORDPRESS_DB_USER
             value: root
           - name: WORDPRESS_DB_HOST
             value: mysql-svc
           - name: WORDPRESS_DB_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: mysql-root-password
                 key: password
      volumes:
      - name: wordpress-persistent-volume
        persistentVolumeClaim:
          claimName: wordpress-persistent-claim
